---
## Author
author:
  name: Мальянц Виктория Кареновна
  orcid: 0000-0002-0877-7063
  email: 1132246740@rudn.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      postal-code: 117198
      city: Москва
      address: ул. Миклухо-Маклая, д. 6

## Title
title: "Реферат"
subtitle: "Биометрия"
license: "CC BY"
---

# Введение

Биометрия - это технология, которая использует уникальные физические или поведенческие характеристики человека для идентификации личности. Актуальность данной темы обусловлена возрастающими требованиями к надежности систем аутентификации в условиях цифровизации. Биометрические технологии представляют собой активно развивающуюся область, находящуюся на стыке компьютерного зрения, информационной безопасности и распознавания образов. Существует множество различных методов, общим для них является необходимость решения задачи преобразования биологического признака в цифровой шаблон с последующим сравнением.

# Виды биометрических данных

Биометрические данные делятся на два вида: физиологические и поведенческие. Существует мультимодальная биометрия - это подход к биометрической идентификации и аутентификации, который предполагает использование двух и более различных типов данных для повышения точности и надежности систем распознавания.

Рассмотрим подробнее виды биометрических данных.

Физиологические:

* Отпечатки пальцев
* Геометрия лица
* Сетчатка глаза
* Радужная оболочка
* ДНК
* Вены ладони
* Вены пальца

Поведенческие:

* Динамика подписи
* Голос
* Походка [@biometric_personal_identification_based_on_the_dynamics_of_subconsciousmovements]
* Клавиатурный почерк

# Принципы работы

Выделим 6 этапов от сенсора до решения.

* Захват. Получение образца сканером, камерой или микрофоном. На данном этапе важно качество полученных данных, а именно разрешение, освещение и шум.
* Предобработка. Удаление шумов, нормализация, нахождение области интереса.
* Извлечение признаков. Алгоритм находит уникальные точки. Например, для лица 80-100 точек, для голоса мел-кепстральные коэффициенты (MFCC), то есть математические представления спектральных характеристик речевого сигнала, которые используются для анализа и распознавания речи, идентификации диктора и других задач обработки аудио.
* Создание биометрического шаблона. Это математический вектор чисел, размер шаблона от 512 байт (палец) до 2-3 килобайт (лицо, радужка). 
* Сравнение. Верификация (проверка подлинности информации, подтверждение достоверности данных) или идентификация (процесс распознавания субъекта в информационной системе по уникальному признаку) [@biometric_systems:_Methods_and_means_of_identifying_a_person’s_identity].
* Принятие решения. Вычисление степени сходства (число от 0 до 1), сравнение с порогом, который настраивает администратор.

# Применение

* Электроника. Сматрфоны, планшеты, ноутбуки, компьютеры, умные колонки, умные часы, фитнес-браслеты.
* Розничная торговля и сфера услуг. Персонализация обслуживания, системы лояльности, кассы самообслуживания.
* Финансовый сектор. Удаленная идентификация клиентов, банкоматы без карты, платежные сервисы, борьба с мошенничеством.
* Аэропорты. Биометрические загранпаспорта.
* Корпоративный сектор. Системы контроля и управления доступом, учет рабочего времени, защита информации на рабочих местах.
* Здравоохранение. Идентификация пациентов, контроль доступа к лекарственным средствам. 
* Транспорт. Бесключевой доступ в автомобили, идентификация водителей коммерческого транспорта, оплата проезда.
* Образование. Контроль посещаемости, прокторинг онлайн-экзаменов, доступ в общежития и библиотеки.

# Заключение

В современном мире биометрические технологии занимают ключевое место в системах идентификации и аутентификации личности. Биометрия использует уникальные, практические не поддающиеся подделке характеристики человека, что обеспечивает высокий уровень безопасности.

# Список литературы{.unnumbered}

::: {#refs}
:::
